import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MaskObserverWrapper from "./_components/MaskObserverWrapper";
import PageTransition from "./_components/PageTransition";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Cohere.img",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <head>
                <link
                    rel="stylesheet"
                    href="https://use.typekit.net/vuf7dry.css"
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <PageTransition>
                    <MaskObserverWrapper>{children}</MaskObserverWrapper>
                </PageTransition>
            </body>
        </html>
    );
}
